;; Load my configuration files.
(add-to-list 'load-path "~/.emacs.d/my-conf")
(load "my-defuns")
(load "my-pkgs")
(load "my-ido")
(load "my-smex")
(load "my-evil")
(load "my-prog")
(load "my-elisp")
(load "my-clojure")
(load "my-text")
(load "my-latex")
(load "my-misc")
(load "my-bindings")
(load "my-theme")
